### ISSUE TITLE
DaemonSet apiVersion should be updated

### ISSUE THREAD

**Issue by radicand** [janekbaraniewski/kubeserial#14]
On Kubernetes 1.17, I get the below crashloop when running this:

`{"level":"error","ts":1585579148.2771335,"logger":"cmd","msg":"Manager exited non-zero","error":"no matches for kind \"DaemonSet\" in version \"apps/v1beta2\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/janek/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\tkubeserial/cmd/manager/main.go:150\nruntime.main\n\t/usr/lib/go/src/runtime/proc.go:203"}`

`apps/v1` is the stable apiVersion since at least K8S v1.14

**Comment by janekbaraniewski** [comment]
hey! Thanks for letting me know, I was testing it on 1.15 where DS was still available in beta2 and missed this. I just released new image with usage of apps/v1.

**Comment by radicand** [comment]
Cheers, just pulled and updated using the stable image, appears to have initialized properly.
